# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LunchTrain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LunchTrain
  # Pods for Playing With Fire
  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'Firebase/Firestore'
  pod 'SnapKit'
  pod 'Firebase/Messaging'

  target 'LunchTrainTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
